include tests in actions

diff --git a/.github/workflows/checks.yml b/.github/workflows/checks.yml
--- a/.github/workflows/checks.yml
+++ b/.github/workflows/checks.yml
@@ -52,33 +52,33 @@ jobs:
 #              exit 1
 #          fi
 #
-#  build:
-#    needs: linting-and-docs
-#
-#    runs-on: ubuntu-latest
-#    strategy:
-#      matrix:
-#        python-version: [3.6, 3.7, 3.8, 3.9, 3.10]
-#
-#    steps:
-#    - name: Checkout repository
-#      uses: actions/checkout@v3
-#    - name: Setup python
-#      uses: actions/setup-python@v3
-#      with:
-#        python-version: ${{ matrix.python-version }}
-#    - name: Install test dependencies
-#      run: |
-#        pip install --upgrade pip wheel
-#        pip install -e .[tests]
-#    - name: Test with pytest
-#      env:
-#        MIN_COVERAGE: 90
-#      run: |
-#          pytest tests -r a --cov=climateforcing --cov-report=''
-#          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
-#          then
-#              echo
-#              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
-#              exit 1
-#          fi
+  build:
+    needs: linting-and-docs
+
+    runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
+
+    steps:
+    - name: Checkout repository
+      uses: actions/checkout@v3
+    - name: Setup python
+      uses: actions/setup-python@v3
+      with:
+        python-version: ${{ matrix.python-version }}
+    - name: Install test dependencies
+      run: |
+        pip install --upgrade pip wheel
+        pip install -e .[tests]
+    - name: Test with pytest
+      env:
+        MIN_COVERAGE: 65
+      run: |
+          pytest tests -r a --cov=climateforcing --cov-report=''
+          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
+          then
+              echo
+              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
+              exit 1
+          fi
